### ISSUE TITLE
Error 'Upload adapter is not defined' with ckeditor-build-classic & ckeditor5-react

### ISSUE THREAD

**Issue by Telemanage** [ckeditor/ckeditor5-react#101]
Using ckeditor5-react and ckeditor5-build-classic

```
import CKEditor from '@ckeditor/ckeditor5-react';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
...

<CKEditor
    editor={ ClassicEditor }
    data=  { value }
    onInit={ editor => {
        // You can store the "editor" and use when it is needed.
        console.log( 'Editor is ready to use!', editor );
        const data = editor.getData();
        console.log( { event, editor, data } );
    } }
    onChange={ ( event, editor ) => {
        console.log( 'Change.', editor );
    } }
    onBlur={ editor => {
        console.log( 'Blur.', editor );
    } }
    onFocus={ editor => {
        console.log( 'Focus.', editor );
    } }
/>
```
The React component CKEditor renders the rich text field in HTML nicely.  But the image upload button does not work, nor does pasting an image.  The error in the browser console is:

> filerepository-no-upload-adapter: Upload adapter is not defined. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-filerepository-no-upload-adapter

I would like to configure the upload adapter to use the Base64UploadAdapter.  How to do that?

**Comment by Mgsy** [comment]
Hello, if you want to use `Base64UploadAdapter`, you should create a custom CKEditor 5 build with this adapter and pass this build to your React component (so, instead of importing `ckeditor5-build-classic`, you'll need to import your custom build). Please, take a look at our guides:
* [Installing plugins guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/installing-plugins.html)
* [Base64 upload adapter documentation](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/base64-upload-adapter.html)
