### ISSUE TITLE
Html Tags appears in the editor

### ISSUE THREAD

**Issue by Edgame2** [ckeditor/ckeditor5-react#154]
When i created the document everything works fined. But when i want to edit, i retrive the document form Mongo pass the result into the state and the state to the editor like so: 

`<CKEditor
                    editor={this.state.editor}
                    data={this.state.content}`

The content appears but the Html also, my guess is that it is coming from React stopping Html Rendering.

![Annotation 2020-05-28 110949_LI](https://user-images.githubusercontent.com/3065270/83128919-f9571980-a0d3-11ea-8edf-4598b4212c7c.jpg)

How can i solve this problem ?

**Comment by FilipTokarski** [comment]
cc @pomek

**Comment by pomek** [comment]
I am sorry for the late response.

I was wondering why the editor renders additional `<p>` elements and I see only two reasons:

1. For some reason, your data could contain those paragraphs. 
2. Something wrong happens when we inject HTML into the div element that is used to create the editor.

ATM, we inject the content passed by the `data` property to the div:

https://github.com/ckeditor/ckeditor5-react/blob/23f4ff176ae475a9f85a663955ba661bce5214c0/src/ckeditor.jsx#L51-L53

In https://github.com/ckeditor/ckeditor5-react/pull/163 we will change it as we should use [`config.initialData`](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-initialData) when specifying the initial data in the editor.

**Comment by Mgsy** [comment]
I'm closing it due to a lack of activity.
