### ISSUE TITLE
Preventing image paste/drop

### ISSUE THREAD

**Issue by mr-moto** [ckeditor/ckeditor5-react#157]
Is there a way to prevent images from being pasted or dropped into the edtior ( without ejecting )?

Ive tried setting `removePlugins: ['Image', 'ImageToolbar', 'ImageCaption', 'ImageStyle', 'ImageUpload']` in config but no luck

**Comment by prithvi2k2** [comment]
@FilipTokarski Is this still valid in v42+ with many changes? I simply can't get it to work. I want to sanitize HTML accd to my requirements before passing content further in ClipboardPipeline and eventually pasting the sanitized HTML into the editor view

**Comment by prithvi2k2** [comment]
Since the docs mention not to use evt.stop() (https://ckeditor.com/docs/ckeditor5/latest/api/module_clipboard_clipboardpipeline-ClipboardInputTransformationEvent.html) while modifying content, and `inputTransformation` event has moved from `Clipboard` to `ClipboardPipeline` - I can safely assume the above snippet of code won't help me, gotta find a way based on latest spec, I'm on v43
