### ISSUE TITLE
How upload Image

### ISSUE THREAD

**Issue by zhouhuiquan** [ckeditor/ckeditor5-react#19]
console.error is filerepository-no-upload-adapter: Upload adapter is not defined
Could you provide a demo? Thanks

**Comment by pomek** [comment]
Did you see [the error documentation](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/support/error-codes.html#error-filerepository-no-upload-adapter)? It exactly describes what do you need to do in order to run the upload.

You can also use [`ckeditor5-easy-image`](https://github.com/ckeditor/ckeditor5-easy-image) plugin but it needs the [Cloud Services](https://ckeditor.com/ckeditor-cloud-services/) which supports the image upload using Easy Image. How to connect Cloud Services, Easy Image and CKEditor5 you can find in [the documentation Cloud Services – Quick start](https://docs.ckeditor.com/cs/latest/guides/easy-image/quick-start.html).

I'm closing this ticket but if you will have more questions, feel free to ask.

**Comment by carlyseitz817** [comment]
Easy Image is way too expensive...I'd much rather use something like AWS or Cloudinary.
