### ISSUE TITLE
How to get the editor value?

### ISSUE THREAD

**Issue by Softwareschmiede** [ckeditor/ckeditor5-react#20]
I implemented the ckeditor-react module described in your documentation.
But there i only get en eventInfo and the editor instance.

How do i get the value the user entered?

**Comment by pomek** [comment]
You have got two ways to do that:

1. Use `onInit` callback in order to save a reference to the editor. Then if the data is needed, call the `editor.getData()`,
2. Listen to data changes in the editor using `onChange` callback. It receives two parameters. The second one is an editor instance. Calling `editor.getData()` returns what you want.

**Comment by Softwareschmiede** [comment]
Ok, i read the docu but i didn't find the getData() method -.-

Sorry and thank you very much.

**Comment by gyanranjan478** [comment]
vv

**Comment by ManuC84** [comment]
@shamseerahammedm  did you happen to solve the clearing value issue?

**Comment by StefoDev** [comment]
> How do you get the editor value outside the CK editor component 

What we did to solve this was to use the `onReady` function that provides the editor instance. Inside that function you can assign the instance to a variable that you control and do what you need to do with it.

```ts
onReady={ editor => {
    // You can store the "editor" and use when it is needed.
    console.log( 'Editor is ready to use!', editor );
} }
```
