### ISSUE TITLE
CKEditor5 showing a black triangle

### ISSUE THREAD

**Issue by zainzin** [ckeditor/ckeditor5-react#235]
After creating a component and configure it as a plugin, I see a black triangle being added in the editor.
![image](https://user-images.githubusercontent.com/13081313/116767020-9795e280-a9fb-11eb-9c80-15f54e67ce9f.png)

**Comment by FilipTokarski** [comment]
Hi, thanks for the report. It seems that similar thing [happened in Angular](https://github.com/ckeditor/ckeditor5-angular/issues/210) some time ago, but in order to look into this, we'll need precise steps to reproduce this and some information about your environment ( package.json, webpack config, etc. )
