### ISSUE TITLE
chinese input bug in safari

### ISSUE THREAD

**Issue by laincarl** [ckeditor/ckeditor5-react#240]
my code 

`
import React, { Component } from "react";
import { CKEditor } from "@ckeditor/ckeditor5-react";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";

class App extends Component {
  render() {
    return (
      <div className="App">
        <h2>Using CKEditor 5 build in React</h2>
        <CKEditor
          editor={ClassicEditor}
          data="<p>Hello from CKEditor 5!</p>"
          onReady={(editor) => {
            // You can store the "editor" and use when it is needed.
            console.log("Editor is ready to use!", editor);
          }}
          onChange={(event, editor) => {
            const data = editor.getData();
            console.log({ event, editor, data });
          }}
          onBlur={(event, editor) => {
            console.log("Blur.", editor);
          }}
          onFocus={(event, editor) => {
            console.log("Focus.", editor);
          }}
        />
      </div>
    );
  }
}

export default App;

`
there is a extra n

https://user-images.githubusercontent.com/19968779/117906475-915f0a80-b307-11eb-8877-4d6edc2a107d.mov

**Comment by FilipTokarski** [comment]
Hi, thank you for the report. This bug is known and it's one of those that will hopefully be fixed when [migration to beforeInput](https://github.com/ckeditor/ckeditor5/issues/7462) is done. However, fixing issues related to IME is not easy and it will require some bigger changes in the editor.
Please keep in mind, that due to lots of other things we're working on, we cannot guarantee any ETA for this.  
  
I'll close this ticket as a duplicate.
