### ISSUE TITLE
Exception after changing a route while using `CKEditorContext`

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-react#349]
### Generic steps to reproduce

1.  Create an app with `<CKEditorContext />` and two routes - one for the sample and the second one for a blank HTML page.
2.  After initializing the editor, change the route.

### Scenario with demo

1.  Download the demo project ([real-time-collaboration-for-react.zip](https://github.com/ckeditor/ckeditor5-react/files/10155629/real-time-collaboration-for-react.zip)) and run it.
2.  After initializing the editor, click on the _Page 2_ button.

## Current result

There are errors in the console:

```javascript
index.js:5 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'then')
    at index.js:5:167077
    at new Promise (<anonymous>)
    at sn._destroyEditor (index.js:5:167023)
    at sn.componentWillUnmount (index.js:5:165891)
    at pc (index.js:5:963026)
    at hc (index.js:5:962117)
    at pc (index.js:5:963200)
    at hc (index.js:5:962117)
    at pc (index.js:5:963068)
    at hc (index.js:5:962117)
    
index.js:5 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'model')
    at index.js:5:159067
```

## Notes

Demo anatomy:

`src/sample.js` - routing definition  
`src/app.js` - the application code

I couldn't reproduce the issue without `<CKEditorContext>` component.

*   `"@ckeditor/ckeditor5-react": "5.0.3"`
*   `"react": "^18.2.0"`,
*   `"react-dom": "^18.2.0"`,
*   `"react-router-dom": "^6.4.3"`,

**Comment by pomek** [comment]
Debug notes:

* We have two errors: the first comes from the react component, and the second reports `ContextWatchdog` (`ckeditor5-watchdog`).
	1. A promise returned by `ContextWatchdog#remove()` is ignored. https://github.com/ckeditor/ckeditor5-react/blob/4d433c57db92993de9ef05e7a896503ab540abe9/src/ckeditor.jsx#L353-L355
	Adding `return` helps.
	2. https://github.com/ckeditor/ckeditor5/blob/0a3431e9828b291ce34053bef471fd1d13b23738/packages/ckeditor5-watchdog/src/editorwatchdog.js#L241
	`EditorWatchdog` tries to detach events from an editor that does not exist anymore.
* Let's focus on the second error.
* We do not have to detach events manually (https://github.com/ckeditor/ckeditor5/blob/0a3431e9828b291ce34053bef471fd1d13b23738/packages/ckeditor5-watchdog/src/editorwatchdog.js#L241), as in the following chain: [editor](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-core/src/editor/editor.ts#L418-L441) > [model](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-engine/src/model/model.ts#L1020-L1026) > [document](https://github.com/ckeditor/ckeditor5/blob/0a3431e9828b291ce34053bef471fd1d13b23738/packages/ckeditor5-engine/src/model/document.ts#L208-L211), it is handled in a `destroy()` method.
* Then, for some reason (I don't know why yet), the [destructor](https://github.com/ckeditor/ckeditor5/blob/0a3431e9828b291ce34053bef471fd1d13b23738/packages/ckeditor5-watchdog/src/editorwatchdog.js#L82) is a called with `null` instead of an editor instance.

To fix the problem, we need to:

* ckeditor5-react: do not ignore a promise,
* ckeditor5-watchdog: do not destroy a destroyed editor (it can be tricky to cover with a unit test).
