### ISSUE TITLE
Questions on custom plugins with react and webpack 4

### ISSUE THREAD

**Issue by indefinitelee** [ckeditor/ckeditor5-react#396]
I'm really just having trouble piecing together the different sections of documentation to understand what the recommended approach is when using CKEditor5 in React (v16.8) with webpack(4.41) and a requirement to create custom plugins. 

I want to exclude certain features from ckeditor such as cloud and collaboration plugins. 

I need to create plugins for new toolbar items which would receive user input. e.g. a Toolbar button which is a phone icon, upon click the user would see a dropdown menu with types of phone numbers to insert, such as Customer Service, Sales, Local Office. 

I don't know if those custom plugins would have dependencies on other plugins. 

I _think_ the build strategy has an influence on the ability to add plugins and how one does it. 

If i just use the quick start react installation` npm install --save @ckeditor/ckeditor5-react @ckeditor/ckeditor5-build-classic` will i have any challenges with building and installing custom plugins?

**Comment by Witoso** [comment]
Hey @indefinitelee! I would advise going with the route that we describe in the React docs as [customizing builds](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/react.html#customizing-the-builds) and i[ntegrating a build from an online builder](https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/react.html#integrating-a-build-from-the-online-builder). This way, you will have a separate folder with the editor and its build process separated from the React build. It will also allow you to write custom plugins.

> If i just use the quick start react installation `npm install --save @ckeditor/ckeditor5-react @ckeditor/ckeditor5-build-classic` will i have any challenges with building and installing custom plugins?

You cannot add plugins to predefined builds. That's why I would propose the method above.

**Comment by indefinitelee** [comment]
thanks for the advice
