### ISSUE TITLE
Cannot find module '@ckeditor/ckeditor5-image'

### ISSUE THREAD

**Issue by amanshu-kataria** [ckeditor/ckeditor5-react#59]
I'm trying to add `@ckeditor/ckeditor5-image` plugin to my react app, but it says cannot find the module even though I added. I'm using custom webpack instead of `create-react-app`, and the webpack configuration is as follows: 
```const path = require('path');

const HtmlWebPackPlugin = require('html-webpack-plugin');
const webpackDashboard = require('webpack-dashboard/plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const InterpolateHtmlPlugin = require('interpolate-html-plugin');
const FriendlyErrorsWebpackPlugin = require('friendly-errors-webpack-plugin');
const ErrorOverlayPlugin = require('error-overlay-webpack-plugin');
const Dotenv = require('dotenv-webpack');

const PORT = 4000;

module.exports = {
  mode: 'development',
  entry: path.join(__dirname, 'src/index.js'),
  devtool: 'inline-source-map',
  output: {
    path: path.join(__dirname, 'build'),
    filename: '[name].js',
    chunkFilename: '[name].js'
  },
  devServer: {
    open: true,
    inline: true,
    contentBase: './public',
    port: PORT,
    publicPath: '/',
    historyApiFallback: true,
    quiet: true
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      },
      {
        test: /\.html$/,
        use: [
          {
            loader: 'html-loader'
          }
        ]
      },
      {
        test: /\.(css)$/,
        use: ['style-loader', 'css-loader']
      }
    ]
  },
  plugins: [
    new Dotenv(),
    new ErrorOverlayPlugin(),
    new CleanWebpackPlugin(['build']),
    new HtmlWebPackPlugin({
      template: path.join(__dirname, '/public/index.html'),
      filename: 'index.html',
      inject: 'body'
    }),
    new webpackDashboard(),
    new MiniCssExtractPlugin({
      filename: '[name].css',
      chunkFilename: '[id].css'
    }),
    new InterpolateHtmlPlugin({
      PUBLIC_URL: './public'
    }),
    new FriendlyErrorsWebpackPlugin({
      compilationSuccessInfo: {
        messages: [`Application is running here http://localhost:${PORT}`]
      }
    })
  ]
};
```
This is how I'm trying to add the plugin:
```
import React, { PureComponent } from 'react';
import CKEditor from '@ckeditor/ckeditor5-react';
import BallonEditor from '@ckeditor/ckeditor5-build-balloon';
import Image from '@ckeditor/ckeditor5-image';

class Editor extends PureComponent {
  render() {
    return (
          <CKEditor
            editor={BallonEditor}
            data="<p>Default Content</p>"
            config={{
              toolbar: [
                'heading',
                '|',
                'bold',
                'italic',
                'link',
                'bulletedList',
                'numberedList',
                'image',
                'mediaEmbed'
              ],
              plugin: [Image],
              }
            }}
            onInit={editor => {
              // You can store the "editor" and use when it is needed.
              console.log('Editor is ready to use!', editor);
            }}
            onChange={(event, editor) => {
              const data = editor.getData();
              console.log({ event, editor, data });
            }}
            onBlur={editor => {
              console.log('Blur.', editor);
            }}
            onFocus={editor => {
              console.log('Focus.', editor);
            }}
          />
    );
  }
}

export default Editor;
```
I restarted the `webpack-dev-server` after installing the dependency, but still doesn't help.

**Comment by pomek** [comment]
You can't add a plugin to the CKEditor 5 Builds. Read more – https://github.com/ckeditor/ckeditor5/issues/1047. If you want to do that, you need to [create a custom build](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/development/custom-builds.html) or [modify your Webpack configuration](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/react.html#integrating-ckeditor-5-built-from-source) in order to use [CKEditor5 Framework](https://ckeditor.com/docs/ckeditor5/latest/framework/index.html).

Why do you want to add the image plugin? `@ckeditor/ckeditor5-build-balloon` [includes the `@ckeditor/ckeditor5-image`](https://github.com/ckeditor/ckeditor5-build-balloon/blob/58592b03577d3e0c8ac07e27c1d0ee329b4696aa/src/ckeditor.js#L44-L48) package and all plugins that the package exports. [See the demo.](https://ckeditor.com/docs/ckeditor5/latest/examples/builds/balloon-editor.html)

**Comment by amanshu-kataria** [comment]
@pomek there's image package in `@ckeditor/ckeditor5-build-balloon` but when I try to upload image it doesn't upload the image. So I thought I need to import the package. I'll try with the other methods you mentioned.

**Comment by pomek** [comment]
> when I try to upload image it doesn't upload the image

I guess you need to create an upload adapter which will handle uploading images. You can read more about it [Image upload overview](https://ckeditor.com/docs/ckeditor5/latest/features/image-upload/image-upload.html) section in the documentation.

CKEditor 5 Builds are integrated with [Easy Image](https://ckeditor.com/ckeditor-cloud-services/easy-image/) service which allows uploading images to the server. It's a paid solution but you can use [30 days free trial](https://orders.ckeditor.com/trial/easy-image) for testing before buying the service.

There is an article in our documentation about [Quick Start with Cloud Services](https://ckeditor.com/docs/cs/latest/guides/easy-image/quick-start.html) that explains how to create an account and what you need to do in order to integrate the build with the Cloud Services.

In case of any questions, let us know and we will try to help you.

**Comment by amanshu-kataria** [comment]
@pomek I tried with modified webpack configuration, it didn't work. It still shows `Module not found`. I'll try with custom with first because I want customized toolbar and when I import `image` plugin shows module not found. Thanks for the help. 👍 💯
