### ISSUE TITLE
CKEditor 5 loading extremely slowly when loading a lot of components

### ISSUE THREAD

**Issue by AustinMutschler** [ckeditor/ckeditor5-react#93]
I am loading about 150 CKEditor components on a page at a time with a lot more to come. When I do this, my page takes about 10 seconds to load. Is there anything I or this project can do to help with the initialization slowness?

**Comment by Reinmar** [comment]
Hi! CKEditor 5 is a quite big application itself. It's powerful, but that power has to come from the underlying architecture. And this architecture comes at non-zero cost. When you multiply this by 150, you get 150 apps suddenly loaded into your memory, into the DOM, you have the cost of initializing it, processing the input, rendering the changes in the DOM and so on and so on. Imagine loading 150 MS Word instances at once (of course, CKE5 << MSWord, but still).

Now, 150 editor instances is **a lot**. No user will ever use all of them at once. I'd advise changing how you initialize your application so it does not load all those instances at once, but rather create them on demand. That can be – when the user first clicks somewhere, or scroll somewhere, etc. You can also reuse the old instances and rather than destroying them, move them to the new place.  It's a bit different scenario, but you can find some inspiration in https://developers.google.com/web/updates/2016/07/infinite-scroller.

PS. There's definitely a lot we could do to improve CKE5's startup time. I guess we could even cut half of it. But if it takes 10s for you right now, then it'll still be 5s. And then you'll realise you need 300 instances. So, I'd rather focus on performance improvements for cases with a reasonable number of instances and reasonable content.

**Comment by AustinMutschler** [comment]
@Reinmar I understand that it is a large application but I think a lot of it has to do with when you render the inline editor in the DOM before the editor is actually clicked instead of on demand. I have already refactored my application to only load the editor when a user clicks on the text that requires editing; however, this causes CKEditor to initialize without selecting the text (The user has to click, the editor initializes, and then click again to actually edit).

Is there some function I can do in the initialize event that auto selects the input as if the user had just clicked on it?

**Comment by AustinMutschler** [comment]
For now, I'm using editor.sourceElement.focus(); in the onInit prop for React and it seems to do what I am looking for; however, is there a better way I could be handling this?
